# Generated by Django 5.2.4 on 2025-10-14 08:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fa-info-circle', help_text="Font Awesome class for pictorial navigation (e.g., 'fa-leaf')", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tip Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Simple, actionable title.', max_length=150)),
                ('summary', models.TextField(help_text='Short summary for list views.', max_length=250)),
                ('full_text', models.TextField(help_text='Full tip details. Must be simple and unambiguous.')),
                ('audio_file', models.FileField(blank=True, help_text='Mandatory audio narration of the tip text for low-literacy users.', null=True, upload_to='tip_audio/')),
                ('citation_source', models.CharField(help_text="Primary source authority (e.g., 'NDOH FBDG', 'NICD Protocol', 'SAMRC Report').", max_length=200)),
                ('citation_url', models.URLField(blank=True, help_text='Direct link to the established fact source document.', max_length=500)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_critical', models.BooleanField(default=False, help_text='Flag for tips requiring immediate visibility (e.g., emergency contacts).')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='tips.tipcategory')),
            ],
            options={
                'verbose_name_plural': 'Health Tips (Verified)',
                'ordering': ['category', '-is_critical', 'title'],
            },
        ),
    ]
