# Generated by Django 5.2.4 on 2025-11-25 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0006_alter_dietaryscreening_added_sugars_daily_and_more'),
        ('facility', '0003_clinic_accepts_referrals_clinic_allow_portal_access_and_more'),
        ('patient', '0008_patient_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('external_provider_name', models.CharField(blank=True, help_text='Name of external provider', max_length=255)),
                ('external_provider_email', models.EmailField(blank=True, help_text='Email of external provider', max_length=254)),
                ('external_provider_phone', models.CharField(blank=True, help_text='Phone of external provider', max_length=20)),
                ('reason', models.TextField(help_text='Brief reason for referral')),
                ('clinical_summary', models.TextField(help_text='Detailed clinical findings and notes')),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('specialty_required', models.CharField(choices=[('general', 'General Dentistry'), ('orthodontics', 'Orthodontics'), ('pediatric', 'Pediatric Dentistry'), ('oral_surgery', 'Oral Surgery'), ('endodontics', 'Endodontics'), ('periodontics', 'Periodontics'), ('prosthodontics', 'Prosthodontics'), ('other', 'Other')], default='general', max_length=30)),
                ('patient_preferences', models.TextField(blank=True, help_text='Patient/parent preferences or concerns')),
                ('insurance_information', models.TextField(blank=True, help_text='Insurance details if applicable')),
                ('delivery_method', models.CharField(blank=True, choices=[('internal', 'Internal System'), ('api', 'API'), ('email', 'Email'), ('sms', 'SMS'), ('portal', 'Portal Link'), ('manual', 'Manual')], max_length=20)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('last_delivery_attempt', models.DateTimeField(blank=True, null=True)),
                ('delivery_error', models.TextField(blank=True, help_text='Error message if delivery failed')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('appointment_scheduled', 'Appointment Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_date', models.DateTimeField(blank=True, help_text='Scheduled appointment with receiving provider', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Referral expiration date')),
                ('access_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('view_count', models.IntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('dental_screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='assessments.dentalscreening')),
                ('dietary_screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='assessments.dietaryscreening')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='patient.patient')),
                ('receiving_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_to', to='facility.clinic')),
                ('receiving_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referring_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_from', to='facility.clinic')),
                ('referring_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='referrals/attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='referrals.referral')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Attachment',
                'verbose_name_plural': 'Referral Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Name if external user', max_length=255)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Whether comment is from internal system user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='referrals.referral')),
            ],
            options={
                'verbose_name': 'Referral Comment',
                'verbose_name_plural': 'Referral Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('internal', 'Internal System'), ('api', 'API'), ('email', 'Email'), ('sms', 'SMS'), ('portal', 'Portal Link'), ('manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('response_data', models.JSONField(blank=True, help_text='API response or other delivery data', null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='referrals.referral')),
            ],
            options={
                'verbose_name': 'Delivery Log',
                'verbose_name_plural': 'Delivery Logs',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_number'], name='referrals_r_referra_13ce98_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['access_token'], name='referrals_r_access__6e0b34_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status'], name='referrals_r_status_50a3e5_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['-created_at'], name='referrals_r_created_ba3fe4_idx'),
        ),
    ]
