# Generated by Django 5.2.4 on 2025-11-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='specialty_required',
        ),
    ]
