# Generated by Django 5.2.4 on 2025-11-30 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_remove_clinic_accepts_referrals_and_more'),
        ('referrals', '0002_remove_referral_specialty_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='receiving_practitioner',
            field=models.ForeignKey(blank=True, help_text='Individual practitioner receiving the referral', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_referrals_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='recommended_profession',
            field=models.CharField(blank=True, help_text='The profession type recommended for this referral', max_length=64),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_type',
            field=models.CharField(choices=[('facility', 'To Facility/Clinic'), ('practitioner', 'To Individual Practitioner')], default='facility', help_text='Whether this referral is to a facility or individual practitioner', max_length=20),
        ),
        migrations.AlterField(
            model_name='referral',
            name='receiving_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals_to', to='facility.clinic'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referring_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals_from', to='facility.clinic'),
        ),
    ]
