# Generated by Django 5.2.4 on 2025-11-30 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_remove_clinic_accepts_referrals_and_more'),
        ('userprofile', '0009_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepts_referrals',
            field=models.BooleanField(default=False, help_text='Whether this practitioner accepts patient referrals'),
        ),
        migrations.AddField(
            model_name='profile',
            name='affiliated_facility',
            field=models.ForeignKey(blank=True, help_text='Primary facility/clinic this practitioner is affiliated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_practitioners', to='facility.clinic'),
        ),
        migrations.AddField(
            model_name='profile',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('unavailable', 'Unavailable'), ('on_leave', 'On Leave')], default='available', help_text='Current availability for accepting new patients', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='consultation_details',
            field=models.TextField(blank=True, help_text='Consultation hours, fees, or other relevant details'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, help_text='Areas of specialization or expertise', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(choices=[('medical_doctor', 'Medical Doctor'), ('dentist', 'Dentist'), ('psychologist', 'Psychologist'), ('physiotherapist', 'Physiotherapist'), ('radiographer', 'Radiographer'), ('occupational_therapist', 'Occupational Therapist'), ('biokineticist', 'Biokineticist'), ('clinical_technologist', 'Clinical Technologist'), ('dietitian', 'Dietitian'), ('audiologist', 'Audiologist'), ('optometrist', 'Optometrist'), ('emergency_care_practitioner', 'Emergency Care Practitioner'), ('registered_nurse', 'Registered Nurse'), ('enrolled_nurse', 'Enrolled Nurse'), ('nursing_assistant', 'Nursing Assistant'), ('midwife', 'Midwife'), ('orthodontist', 'Orthodontist'), ('oral_surgeon', 'Oral Surgeon'), ('periodontist', 'Periodontist'), ('endodontist', 'Endodontist'), ('pediatric_dentist', 'Pediatric Dentist'), ('prosthodontist', 'Prosthodontist'), ('oral_pathologist', 'Oral Pathologist'), ('pediatrician', 'Pediatrician')], default='dentist', max_length=64),
        ),
    ]
