# Generated by Django 5.2.4 on 2025-12-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_profile_accepts_referrals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_end_time',
            field=models.TimeField(blank=True, default='17:00', help_text="Practitioner's end time", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_start_time',
            field=models.TimeField(blank=True, default='08:00', help_text="Practitioner's start time", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_days',
            field=models.JSONField(blank=True, default=list, help_text='List of working days (0=Monday, 6=Sunday). Default: [0,1,2,3,4] (Mon-Fri)'),
        ),
    ]
