# Generated by Django 5.2.4 on 2026-03-01 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_profile_work_end_time_profile_work_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='work_end_time',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), help_text="Practitioner's end time", null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_start_time',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), help_text="Practitioner's start time", null=True),
        ),
    ]
