# Generated by Django 5.2.4 on 2025-12-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_dietaryscreening_added_sugars_daily_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalscreening',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='True if this is a saved draft, False if completed'),
        ),
        migrations.AddField(
            model_name='dentalscreening',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
