# Generated by Django 5.2.4 on 2025-11-25 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_clinic_clinic_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='accepts_referrals',
            field=models.BooleanField(default=True, help_text='Whether this clinic accepts referrals'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='allow_portal_access',
            field=models.BooleanField(default=True, help_text='Allow viewing referrals via secure portal link'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='api_endpoint',
            field=models.URLField(blank=True, help_text='API endpoint for receiving referrals', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='api_format',
            field=models.CharField(blank=True, choices=[('fhir', 'FHIR Standard'), ('custom', 'Custom JSON'), ('hl7', 'HL7 v2')], help_text='API data format', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='api_key',
            field=models.CharField(blank=True, help_text='API authentication key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='associated_users',
            field=models.ManyToManyField(blank=True, help_text='OralSmart users associated with this clinic', related_name='clinics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinic',
            name='email_notification_enabled',
            field=models.BooleanField(default=True, help_text='Send email notifications for referrals'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='has_api_integration',
            field=models.BooleanField(default=False, help_text='Does this clinic have API integration?'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='preferred_method',
            field=models.CharField(choices=[('internal', 'Internal System'), ('api', 'API Integration'), ('email', 'Email'), ('sms', 'SMS'), ('portal', 'Secure Portal')], default='email', help_text='Preferred method for receiving referrals', max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='referral_email',
            field=models.EmailField(blank=True, help_text='Email address for receiving referrals', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='require_authentication',
            field=models.BooleanField(default=True, help_text='Require additional authentication for portal access'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='sms_notification_enabled',
            field=models.BooleanField(default=False, help_text='Send SMS notifications for referrals'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='sms_number',
            field=models.CharField(blank=True, help_text='Phone number for SMS notifications', max_length=20, null=True),
        ),
    ]
