# Generated by Django 5.2.4 on 2025-11-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_clinic_accepts_referrals_clinic_allow_portal_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='accepts_referrals',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='allow_portal_access',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='api_endpoint',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='api_format',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='associated_users',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='email_notification_enabled',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='has_api_integration',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='preferred_method',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='referral_email',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='require_authentication',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='sms_notification_enabled',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='sms_number',
        ),
    ]
