# Generated by Django 5.2.4 on 2025-11-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_remove_clinic_accepts_referrals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='accepts_referrals',
            field=models.BooleanField(default=True, help_text='Whether this clinic accepts referrals'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='referral_email',
            field=models.EmailField(blank=True, help_text='Email for receiving referrals (if different from main email)', max_length=254, null=True),
        ),
    ]
