# Generated by Django 5.2.4 on 2025-12-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0005_clinic_accepts_referrals_clinic_referral_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='closing_time',
            field=models.TimeField(default='17:00', help_text='Clinic closing time'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='opening_time',
            field=models.TimeField(default='08:00', help_text='Clinic opening time'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='working_days',
            field=models.JSONField(blank=True, default=list, help_text='List of working days (0=Monday, 6=Sunday). Default: [0,1,2,3,4] (Mon-Fri)'),
        ),
    ]
