# Generated by Django 5.2.4 on 2026-03-01 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0006_clinic_closing_time_clinic_opening_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='closing_time',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Clinic closing time'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='opening_time',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Clinic opening time'),
        ),
    ]
